require("items.apple")
require("items.aerospace_mode")
require("items.workspaces")
-- front_app is loaded from workspaces.lua after async workspace creation
require("items.media")
require("items.stats")
require("items.pomodoro")
require("items.volume")
require("items.battery")
require("items.calendar")
